version: '3'

services:

  data-storage:
    image: postgres:latest
    container_name: postgres-local
    hostname: postgres.local.ru
    environment:
      POSTGRES_USER: "local"
      POSTGRES_PASSWORD: "local"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - dockerlocal

  message-broker:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq-local
    hostname: rabbitmq.local.ru
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      # - rabbitmqdata:/var/lib/rabbitmq
      # - "./rabbitmq:/etc/reminder/"
      - type: bind
        source: ./rabbitmq/logs
        target: /var/log/rabbitmq/
      - type: bind
        source: ./rabbitmq/data
        target: /var/lib/rabbitmq/mnesia/
    networks:
      - dockerlocal
    # environment:
    #   - RABBITMQ_CONFIG_FILE=/etc/reminder/rabbitmq.conf

  # pgadmin:
  #   container_name: pgadmin-local
  #   image: dpage/pgadmin4:5.7
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "local@local.com"
  #     PGADMIN_DEFAULT_PASSWORD: "local"
  #     PGADMIN_CONFIG_SERVER_MODE: "False"
  #   volumes:
  #     - ./pgadmin:/var/lib/pgadmin
  #   ports:
  #     - "5050:80"
  #   restart: unless-stopped
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 1G
  #   networks:
  #     - dockerlocal

networks:
  dockerlocal:
    name: dockerlocal
    driver: bridge

# volumes:
#   postgresdata:
#     external: true
#   rabbitmqdata:
#     external: true